title: DIVIN.DEV - Láº­p trÃ¬nh Flutter/Dart 
author:
  name: divin.dev
  email: hocbaicungcon@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
> Learn to Code - for Free, Hour of Code, Learn to Code - Coding Courses for Dev
ğŸ¯ Dart Flutter Framework: Build Native Apps on iOS and Android From a Single Codebase. Download and Build Today. Start With Fully-Customizable Widgets To Build Native Interfaces In Minutes. Open Source.
ğŸ’» CÃ¡c bÃ i giáº£ng vá» thuáº­t toÃ¡n sá»­ dá»¥ng ngÃ´n ngá»¯ láº­p trÃ¬nh Dart
ğŸ’» Video hÆ°á»›ng dáº«n láº­p trÃ¬nh Flutter, tá»± há»c Flutter Ä‘á»ƒ lÃ m app cho Android, iOS, Web...
ğŸ’» Chia sáº» cÃ¡c ebook, tÃ i liá»‡u, sÃ¡ch vá»Ÿ vá» Flutter Development...

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  hocbaicungcon
    # devto: jekyll
    # dribbble: jekyll
    facebook: hocbaicungcon
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    youtube: dartflutter
    youtube_channel: UCgIYfUVE3b__5Aq91CMllvw
    youtube_channel_name: dartflutter
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
